### ISSUE TITLE
Unable to get main.py to open google sheet

### ISSUE THREAD

**Issue by SpectrumFRC3847** [Mechanical-Advantage/AdvantageTrack#1]
Thank you for creating this and making it open to other teams. 

We are trying to get it running on a windows PC and having trouble getting it to connect to the google drive sheet.

The sheet is shared with the service account and we believe we have followed all the directions.

![image](https://user-images.githubusercontent.com/13025464/184510338-72734c51-e12b-476a-9a56-c924d3f6c782.png)

Any suggestions on how to fix this?

Separate note that we don't think is relevant yet:
Getting fping for windows was a little weird, is their a binary you recommend? We are using the one from here - https://www.softpedia.com/get/Network-Tools/IP-Tools/Fping.shtml

**Comment by jwbonner** [comment]
I'm not immediately sure of what the issue could be, and I also apparently lacked the foresight to print a more descriptive error message. I just pushed a new commit that displays the full text of the error when connecting to Google. Could you try the new version and let me know what it says?

I don't a specific recommendation for a Windows fping binary. If the one you found works correctly (once you get that far), I can definitely add it to the README.

**Comment by SpectrumFRC3847** [comment]
Thank you the error message helped, we hadn't enabled the Google Sheets API. We'll update about fping when we get there.
