### ISSUE TITLE
Google API "Read Requests" Quota Exceeded

### ISSUE THREAD

**Issue by SpectrumFRC3847** [Mechanical-Advantage/AdvantageTrack#3]
After running for a while, while unable to ping devices, we are getting a quota exceeded error from the Google API.

![image](https://user-images.githubusercontent.com/13025464/184550000-6f50c310-1ffe-4e04-82cc-10c1c2a42d9e.png)

**Comment by jwbonner** [comment]
Could you post the full log file? You should be able to wait a minute for the quota to reset and then restart it without getting the error (briefly).

When idling, I typically see about 18 requests/minute (the quota is 60 requests/minute). But I also had to fix at least one bug that caused repeated signed out requests, so I would guess there's something similar getting stuck in a loop.

**Comment by SpectrumFRC3847** [comment]
Seems to be fixed now as well, we'll update if the problem comes back.
